# Phần 1: Phép khử Gauss và Các Ứng Dụng
Các hàm được cài đặt từ đầu (from scratch), không dùng NumPy/SciPy/SymPy cho thuật toán.

## Demo — Kiểm thử các trường hợp

In [10]:
import numpy as np
from gaussian import gaussian_eliminate
from determinant import determinant
from inverse import inverse
from rank_basis import rank_and_basis


def verify_solution(A, x, b):
    print("\n" + "="*20 + " KIỂM CHỨNG VỚI NUMPY " + "="*20)
    A_np = np.array(A, dtype=float)
    b_np = np.array(b, dtype=float)

    if isinstance(x, list) and all(isinstance(v, (int, float)) for v in x):
        residual = np.linalg.norm(A_np @ np.array(x, dtype=float) - b_np)
        print(f"1. Sai số hệ phương trình ||Ax - b|| = {residual:.2e}")
    elif isinstance(x, tuple):
        x_coef, free_cols = x
        x0 = np.array([x_coef[j][0] for j in range(len(x_coef))])
        residual = np.linalg.norm(A_np @ x0 - b_np)
        print(f"1. ||Ax₀ - b|| (nghiệm đặc biệt, ti=0) = {residual:.2e}")
    else:
        print(f"1. {x}")

    if A_np.shape[0] == A_np.shape[1]:
        det_self = determinant(A)
        det_np = np.linalg.det(A_np)
        print(f"2. Định thức: Tự tính = {det_self:.4f}, NumPy = {det_np:.4f}")

    rank_self, _, _, _ = rank_and_basis(A)
    rank_np = np.linalg.matrix_rank(A_np)
    print(f"3. Hạng ma trận: Tự tính = {rank_self}, NumPy = {rank_np}")

    if A_np.shape[0] == A_np.shape[1] and abs(np.linalg.det(A_np)) > 1e-12:
        inv_self_res = inverse(A)
        if isinstance(inv_self_res, list):
            inv_error = np.linalg.norm(np.array(inv_self_res) - np.linalg.inv(A_np))
            print(f"4. Sai số ma trận nghịch đảo: {inv_error:.2e}")
        else:
            print(f"4. Nghịch đảo: {inv_self_res}")
    print("="*60)

In [11]:
# ── Demo 1: Nghiệm duy nhất ──────────────────────────────────
print("="*55)
print("  Demo 1: Hệ 3x3 — nghiệm duy nhất")
print("="*55)
A = [[2, 1, -1], [-3, -1, 2], [-2, 1, 2]]
b = [8, -11, -3]
M, x, s = gaussian_eliminate(A, b)
print(f"  Nghiệm: x = {[round(v, 4) for v in x]}")
verify_solution(A, x, b)

  Demo 1: Hệ 3x3 — nghiệm duy nhất
  Nghiệm: x = [2.0, 3.0, -1.0]

==================== KIỂM CHỨNG VỚI NUMPY ====================
1. Sai số hệ phương trình ||Ax - b|| = 8.88e-16
2. Định thức: Tự tính = -1.0000, NumPy = -1.0000
3. Hạng ma trận: Tự tính = 3, NumPy = 3
4. Sai số ma trận nghịch đảo: 4.93e-15


In [12]:
# ── Demo 2: Vô số nghiệm — 1 biến tự do ─────────────────────
print("="*55)
print("  Demo 2: Hệ 3x3 suy biến — vô số nghiệm")
print("="*55)
A = [[1, 2, 3], [2, 4, 6], [1, 1, 1]]
b = [6, 12, 3]
M, x, s = gaussian_eliminate(A, b)
verify_solution(A, x, b)

  Demo 2: Hệ 3x3 suy biến — vô số nghiệm

  ── Nghiệm tổng quát ──
  x1 = t1
  x2 = 3 - 2*t1
  x3 = t1

  ── Dạng vector ──
  x = (0, 3, 0)
      + t1 * (1, -2, 1)

==================== KIỂM CHỨNG VỚI NUMPY ====================
1. ||Ax₀ - b|| (nghiệm đặc biệt, ti=0) = 0.00e+00
2. Định thức: Tự tính = 0.0000, NumPy = 0.0000
3. Hạng ma trận: Tự tính = 2, NumPy = 2


In [14]:
# ── Demo 3: Vô số nghiệm — 2 biến tự do ─────────────────────
print("="*55)
print("  Demo 3: Hệ 3x3 suy biến nặng — 2 biến tự do")
print("="*55)
A = [[1, 2, 4], [2, 4, 8], [3, 6, 12]]
b = [2, 4, 6]
M, x, s = gaussian_eliminate(A, b)

  Demo 3: Hệ 3x3 suy biến nặng — 2 biến tự do

  ── Nghiệm tổng quát ──
  x1 = 2 - 2*t1 - 4*t2
  x2 = t1
  x3 = t2

  ── Dạng vector ──
  x = (2, 0, 0)
      + t1 * (-2, 1, 0)
      + t2 * (-4, 0, 1)


In [15]:
# ── Demo 4: Vô nghiệm ────────────────────────────────────────
print("="*55)
print("  Demo 4: Hệ vô nghiệm")
print("="*55)
A = [[1, 2], [2, 4]]
b = [3, 7]
M, x, s = gaussian_eliminate(A, b)
print(f"  Kết quả: {x}")

  Demo 4: Hệ vô nghiệm
  Kết quả: Hệ phương trình vô nghiệm.


In [16]:
# ── Demo 5: Định thức ────────────────────────────────────────
print("="*55)
print("  Demo 5: Tính định thức")
print("="*55)
A3 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
print(f"  det(A) = {determinant(A3):.4f}  (NumPy: {np.linalg.det(A3):.4f})")

B = [
    [4, 3, 2, 1],
    [1, 2, 3, 4],
    [5, 0, 0, 5],
    [2, 2, 1, 1]
]
print(f"  det(B) = {determinant(B):.4f}  (NumPy: {np.linalg.det(B):.4f})")

A_sing = [[1, 2], [2, 4]]
print(f"  det(ma trận suy biến) = {determinant(A_sing)}  (đúng: 0)")

  Demo 5: Tính định thức
  det(A) = 1.0000  (NumPy: 1.0000)
  det(B) = 50.0000  (NumPy: 50.0000)
  det(ma trận suy biến) = 0.0  (đúng: 0)


In [17]:
# ── Demo 6: Ma trận nghịch đảo ───────────────────────────────
print("="*55)
print("  Demo 6: Ma trận nghịch đảo")
print("="*55)
A3 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
inv_A = inverse(A3)
if isinstance(inv_A, list):
    print("  A^-1 =")
    for row in inv_A:
        print(f"    {[round(v, 4) for v in row]}")
    err = np.linalg.norm(np.array(inv_A) - np.linalg.inv(A3))
    print(f"  ||inv_self - inv_numpy|| = {err:.2e}")

print()
B = [
    [1, 0, 2, 1],
    [0, 1, 0, 2],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
]

inv_B = inverse(B)

if isinstance(inv_B, list):
    print("  B^-1 =")
    for row in inv_B:
        # Sử dụng :>8.4f để các cột thẳng hàng, dễ nhìn hơn
        print("    [" + " ".join(f"{v:>8.4f}" for v in row) + "]")
    
    # Kiểm tra sai số với NumPy
    err4 = np.linalg.norm(np.array(inv_B) - np.linalg.inv(B))
    print(f"\n  ||inv_self - inv_numpy|| = {err4:.2e}")
else:
    print(f"  Kết quả: {inv_B}")

print()
print("  Ma trận không khả nghịch:")
A_sing = [[1, 2], [2, 4]]
print(f"  {inverse(A_sing)}")

  Demo 6: Ma trận nghịch đảo
  A^-1 =
    [-24.0, 18.0, 5.0]
    [20.0, -15.0, -4.0]
    [-5.0, 4.0, 1.0]
  ||inv_self - inv_numpy|| = 1.77e-13

  B^-1 =
    [ -0.3333   1.0000   0.6667  -1.6667]
    [  0.0000  -1.0000   0.0000   2.0000]
    [  0.6667  -1.0000  -0.3333   1.3333]
    [ -0.0000   1.0000  -0.0000  -1.0000]

  ||inv_self - inv_numpy|| = 1.11e-16

  Ma trận không khả nghịch:
  Thông báo: Không có pivot tại cột 2. Ma trận không khả nghịch.


In [18]:
# ── Demo 7: Hạng và cơ sở ────────────────────────────────────
print("="*55)
print("  Demo 7: Hạng và cơ sở ")
print("="*55)
A = [[1, 2, 3], [2, 4, 6], [1, 1, 1]]
rank, col_b, row_b, null_b = rank_and_basis(A)

print(f"Test case 1")
print(f"  Hạng: {rank}  (NumPy: {np.linalg.matrix_rank(A)})")
print(f"  Cơ sở không gian cột  : {col_b}")
print(f"  Cơ sở không gian dòng : {[[round(v,4) for v in r] for r in row_b]}")
print(f"  Cơ sở không gian nghiệm ({len(null_b)} vector):")
for v in null_b:
    check = np.array(A, dtype=float) @ np.array(v)
    print(f"    {[round(v, 4) for v in v]}  →  Av = {np.round(check, 10).tolist()}")

A_rect = [
    [1, 2, 0, 1],
    [0, 1, 1, 0],
    [1, 3, 1, 1]
]
rank_r, col_r, row_r, null_r = rank_and_basis(A_rect)

print(f"Test case 2")
print(f"  Hạng: {rank_r}  (NumPy: {np.linalg.matrix_rank(A_rect)})")
print(f"  Cơ sở không gian cột  : {col_r}")
print(f"  Cơ sở không gian dòng : {[[round(v,4) for v in r] for r in row_r]}")
print(f"  Cơ sở không gian nghiệm ({len(null_r)} vector):")
for v in null_r:
    check = np.array(A_rect, dtype=float) @ np.array(v)
    print(f"    {[round(v, 4) for v in v]}  →  Av = {np.round(check, 10).tolist()}")


A_rank1 = [
    [1, 1, 1],
    [2, 2, 2],
    [-1, -1, -1]
]
rank1, col1, row1, null1 = rank_and_basis(A_rank1)

print(f"Test case 3")
print(f"  Hạng: {rank1}  (NumPy: {np.linalg.matrix_rank(A_rank1)})")
print(f"  Cơ sở không gian cột  : {col1}")
print(f"  Cơ sở không gian dòng : {[[round(v,4) for v in r] for r in row1]}")
print(f"  Cơ sở không gian nghiệm ({len(null1)} vector):")
for v in null1:
    check = np.array(A_rank1, dtype=float) @ np.array(v)
    print(f"    {[round(v, 4) for v in v]}  →  Av = {np.round(check, 10).tolist()}")

  Demo 7: Hạng và cơ sở 
Test case 1
  Hạng: 2  (NumPy: 2)
  Cơ sở không gian cột  : [[1, 2, 1], [2, 4, 1]]
  Cơ sở không gian dòng : [[2, 4, 6], [0.0, -1.0, -2.0]]
  Cơ sở không gian nghiệm (1 vector):
    [1.0, -2.0, 1.0]  →  Av = [0.0, 0.0, 0.0]
Test case 2
  Hạng: 2  (NumPy: 2)
  Cơ sở không gian cột  : [[1, 0, 1], [2, 1, 3]]
  Cơ sở không gian dòng : [[1, 2, 0, 1], [0.0, 1.0, 1.0, 0.0]]
  Cơ sở không gian nghiệm (2 vector):
    [2.0, -1.0, 1.0, 0.0]  →  Av = [0.0, 0.0, 0.0]
    [-1.0, -0.0, 0.0, 1.0]  →  Av = [0.0, 0.0, 0.0]
Test case 3
  Hạng: 1  (NumPy: 1)
  Cơ sở không gian cột  : [[1, 2, -1]]
  Cơ sở không gian dòng : [[2, 2, 2]]
  Cơ sở không gian nghiệm (2 vector):
    [-1.0, 1.0, 0.0]  →  Av = [0.0, 0.0, 0.0]
    [-1.0, 0.0, 1.0]  →  Av = [0.0, 0.0, 0.0]
